#Login Configuration
#Tue Dec 23 18:18:12 CST 2025
comment=\u5B66\u751F\u5BBF\u820D\u7BA1\u7406\u7CFB\u7EDF - \u767B\u5F55\u914D\u7F6E
password=\=ECNyAjM5V2StVGdzl3UtJ3bENjMx4WatRWY
remember=true
username=admin
usertype=ADMIN
