#Login Configuration
#Sat Dec 27 18:04:32 CST 2025
comment=\u5B66\u751F\u5BBF\u820D\u7BA1\u7406\u7CFB\u7EDF - \u767B\u5F55\u914D\u7F6E
password=hQjMwITeltUblR3c5NVby9GR2UDNzITM
remember=true
username=2414110203
usertype=STUDENT
